#include "mainwindow.h"
#include "SVGparser.h"
#include <QMenuBar>
#include <QFileDialog>
#include <QMessageBox>
#include <QApplication>
void MainWindow::setupMenubar() {   // Setup function
    QToolBar *fileBar = addToolBar("Command Bar");  // FIleBar made 
    fileBar->setMovable(false); // Generally not movable the filebar
    fileBar->setIconSize(QSize(30, 30));        // ICON size for menubar set to 30*30
    auto addCmd = [&](const QString &name, const QString &icon, auto slot, const QKeySequence &key = QKeySequence()) { // Functor to setup all actions in less lines
        QAction *act = fileBar->addAction(QIcon(icon), name, this, slot);   // addCmd allows to define actions easily through function call
        if(!key.isEmpty()) act->setShortcut(key);   // QIcon make icon from image at iconPath and sets shortcut key
        return act;
    };
    addCmd("Close", ":/icons/close.svg", &MainWindow::close, QKeySequence::Close);  //Signal initialization and linking to slots predefined
    addCmd("New", ":/icons/new.svg", &MainWindow::newfile, QKeySequence::New);
    addCmd("Open", ":/icons/open.svg", &MainWindow::openfile, QKeySequence::Open);
    addCmd("Save", ":/icons/save.svg", &MainWindow::savefile, QKeySequence::Save);
    addCmd("Save As", ":/icons/saveas.svg", &MainWindow::saveAs, QKeySequence::SaveAs);
    fileBar->addSeparator();
    addCmd("Undo", ":/icons/undo.svg", &MainWindow::undo, QKeySequence::Undo);
    addCmd("Redo", ":/icons/redo.svg", &MainWindow::redo, QKeySequence::Redo);
    fileBar->addSeparator();
    addCmd("Cut", ":/icons/cut.svg", &MainWindow::cut, QKeySequence::Cut);
    addCmd("Copy", ":/icons/copy.svg", &MainWindow::copy, QKeySequence::Copy);
    addCmd("Paste", ":/icons/paste.svg", &MainWindow::paste, QKeySequence::Paste);
    addCmd("Delete", ":/icons/delete.svg", &MainWindow::erase, QKeySequence::Delete);
    addToolBar(Qt::TopToolBarArea, fileBar);    // toolBar kept at top
}
void MainWindow::newfile() {    
    diagramObjects.clear();     // Clears exsisting modelVector , scene and filePath to start everything from scratch
    scene->clear();
    currentFilePath.clear();
    updateSceneFromModel();     // Update scene from model vector since empty will result in empty scene
}
void MainWindow::savefile() {
    if (currentFilePath.isEmpty()) return saveAs(); //Empty filePath launches SaveAs command
    QFile file(currentFilePath);    //Qt file handler object at given path
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {    // Attempts to open file in writeOnly state on disk to prevent crash if it fails
        std::string content = SVGParser::exportToSVG(diagramObjects, 800, 600); // Content to be written generated by exportToSVG function
        file.write(content.c_str());    // Writing content
    }
}
void MainWindow::saveAs() {
    QString fileName = QFileDialog::getSaveFileName(this, "Save SVG", "", "SVG Files (*.svg);;All Files (*)");  // Opens Qt filedialog and gives currentFilePath
    if (fileName.isEmpty()) return; //Empty path return; to prevent crash
    if (!fileName.endsWith(".svg", Qt::CaseInsensitive)) fileName += ".svg";    // .svg made mandatory for file visibility
    currentFilePath = fileName; // Filepath updated
    savefile(); // Passes to save file 
}
void MainWindow::openfile() {
    QString path = QFileDialog::getOpenFileName(this, "Open SVG", "", "SVG Files (*.svg);;All Files (*)");  //Qt file dialog return filepath
    if (path.isEmpty()) return;
    QFile file(path);   //FIlehandler object
    if (file.open(QIODevice::ReadOnly)) {   // Readonly state of file
        currentFilePath = path;
        diagramObjects.clear();
        SVGParser::importFromSVG(file.readAll().toStdString(), diagramObjects); // reading entire file as string and storing in diagram Objects
        updateSceneFromModel(); // Updating as diagramObjects updated
    }
}
void MainWindow::undo() {   // Undo stack empty passes as error but to prevent crash
    if (undo_s.empty()) return;
    redo_s.push(std::move(diagramObjects)); // moves diagramObject to redo stack
    diagramObjects = std::move(undo_s.top());   // make current diagramObject as top of undo stack
    undo_s.pop();   // poping top undo element 
    updateSceneFromModel(); //New diagramObject meaning new scene updation
}void MainWindow::redo() {   // Same as undo just reversed
    if (redo_s.empty()) return;
    undo_s.push(std::move(diagramObjects));
    diagramObjects = std::move(redo_s.top());
    redo_s.pop();
    updateSceneFromModel();
}
void MainWindow::cut() {copy();erase();}    // Essentially copy the object and erasing it
void MainWindow::copy() {                   // Making clone of selected object and storing in prev
    if (auto sel = scene->getSelectedObject()) {prev = sel->clone();}
}void MainWindow::paste() {      //paste works by taking prev object and then
    if (!prev) return;
    saveState();
    auto newItem = prev->clone();   //create a deep copy of object 
    QPoint globalPos = QCursor::pos();  // cursor position globally 
    QPoint viewPos = view->mapFromGlobal(globalPos);        // wrt to our view
    QPointF scenePos = view->mapToScene(viewPos);   // wrt to our scene
    newItem->pastePos(scenePos.x(), scenePos.y());  // pastePos function specific to each object called
    diagramObjects.push_back(std::move(newItem));   // move the unique_ptr ownership to diagramObjects
    updateSceneFromModel(); //changed diagramObjects
}void MainWindow::erase() {
    GraphicsObject* sel = scene->getSelectedObject();   // Get selected obj
    if (!sel) return;   // if not, return and dont crash
    saveState();    // saveState before deletion
    for (auto it = diagramObjects.begin(); it != diagramObjects.end(); ++it) { 
        if (it->get() == sel) {  // Gives iterator value after shifting the objects from selected objects removal to end
            diagramObjects.erase(it);break; // Delete just this one
        }
    }scene->clearSelection();updateSceneFromModel();
}